import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { AppProvider } from "@/components/providers/app-provider";

import { AppFooter } from "./app-footer";
import { AppHeader } from "./app-header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <AppProvider>
          <div className="flex max-h-screen min-h-screen flex-col">
            <AppHeader />
            {children}
            <AppFooter />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
